# Generated by Django 4.0.10 on 2023-10-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('price', models.IntegerField(db_column='Price')),
                ('pictureurl', models.TextField(blank=True, db_column='PictureUrl', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('brand', models.TextField(blank=True, db_column='Brand', null=True)),
                ('quantityinstock', models.IntegerField(db_column='QuantityInStock')),
            ],
            options={
                'db_table': 'Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoppingcartitems',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('productid', models.IntegerField(db_column='ProductId')),
            ],
            options={
                'db_table': 'ShoppingCartItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoppingcarts',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('buyerid', models.TextField(blank=True, db_column='BuyerId', null=True)),
            ],
            options={
                'db_table': 'ShoppingCarts',
                'managed': False,
            },
        ),
    ]
